############################################################################
# apps/examples/mmutest/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_MMUTEST_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_MMUTEST_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_MMUTEST_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_MMUTEST)

MAINSRC = mmutest_main.c

include $(APPDIR)/Application.mk
